version: '3.7'

services: 
  database:
    image: postgres:alpine
    container_name: database_doeme
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=doeme.root
      - POSTGRES_PASSWORD=\5FwH-PVedWWLh*%
      - POSTGRES_DB=pg_doeme
    volumes: 
      - pgdata:/data/postgres
  app: 
    build: .
    container_name: 'doeme'
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database
volumes: 
  pgdata:
    driver: local